# 7.2 - Pandas
***
Pandas is a powerful Python library used for data manipulation and analysis.

### Why Pandas?
- Provides two primary data structures: **Series** and **DataFrames**.
- Built on top of **NumPy**, making it efficient for numerical and tabular data.
- Ideal for working with real-world datasets like CSV files, Excel sheets, and databases.

## Importing Pandas

- Import the pandas library and give it the alias `pd`, which is the standard convention.

In [1]:
import pandas as pd

## Creating Pandas Series and DataFrames

- Create a **Series**, which is a one-dimensional labeled array.

In [2]:
pd.Series([10, 20, 30])

0    10
1    20
2    30
dtype: int64

- Create a **DataFrame** from a Python dictionary. Each key becomes a column.

In [3]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'Dana'], 'Age': [25, 30, 35, 42]}
df = pd.DataFrame(data)
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3     Dana   42

### Understanding the Index in Series and DataFrames
- Every Series and DataFrame in pandas has an **index**.
- The index labels each row, separating Series from plain NumPy arrays or Python lists.
- You can access the index using `.index` and the data using `.values`.
- The `.values` method returns the data as a NumPy array.

In [4]:
series = pd.Series([10, 20, 30])
print("Index:", list(series.index))
print("Values:", series.values)

Index: [0, 1, 2]
Values: [10 20 30]

### Working with DataFrame Columns
- In long form data, the columns are often called **features**, and the values in the column are called **levels**
- we can access column names using `df.columns`.

In [5]:
df.columns

Index(['Name', 'Age'], dtype='object')

- we can add a new column to the datafrane by using a list or by combining existing columns.

In [6]:
# Add new column with list
df['Country'] = ['USA', 'USA', 'Canada', 'France']
df

      Name  Age Country
0    Alice   25     USA
1      Bob   30     USA
2  Charlie   35  Canada
3     Dana   42  France

- We can also combine existing columns to make new columns. Here we use the method `.astype()` to convert the `Age` column from `int` to `str`.

In [7]:
# Add column combining name and age
df['Name_Age'] = df['Name'] + ' (' + df['Age'].astype(str) + ')'
df

      Name  Age Country      Name_Age
0    Alice   25     USA    Alice (25)
1      Bob   30     USA      Bob (30)
2  Charlie   35  Canada  Charlie (35)
3     Dana   42  France     Dana (42)

- You can add new rows using `pd.concat()` or `df.loc[new_index] = new_row` style.

In [8]:
# Add a new row using loc
# row index 4 to add to the end
df.loc[4] = ['Edgar', 28, 'Canada', 'Edgar (28)']
df

      Name  Age Country      Name_Age
0    Alice   25     USA    Alice (25)
1      Bob   30     USA      Bob (30)
2  Charlie   35  Canada  Charlie (35)
3     Dana   42  France     Dana (42)
4    Edgar   28  Canada    Edgar (28)

## Useful DataFrame Methods

- When first encountering data in a dataframe, we often want to understand some general properties of the data. Here are some useful pandas methods for summarizing your data.

- Use `.head(n)` to preview the first `n` rows of the DataFrame (`n=5` by default).

In [ ]:
df.head(2)

- use .sample(n) to randomnly select `n` rows of the DataFrame (`n=1` by default).

In [ ]:
df.sample(2)

- Use `.info()` to see summary information including data types and non-null counts.

In [ ]:
df.info()

- Use `.describe()` to compute basic statistics for numeric columns.

In [ ]:
df.describe()

- Use `.shape` to view the number of rows and columns in the DataFrame.

In [ ]:
df.shape

There are many more useful data

## Indexing, Slicing and Filtering DataFrames

- Access a single column of the DataFrame using bracket notation.

In [ ]:
df['Name']

- Use `.iloc[]` to access rows by index position.

In [ ]:
df.iloc[0]

- Use `.loc[]` to access a specific cell by row label and column name.

In [ ]:
df.loc[0, 'Name']

- We can slice multiple rows and select multiple columns at once.

In [ ]:
df.loc[0:2, ["Age", "Country"]]

- We can filter a dataframe for specific properties by using comparison operators. These apply element-wise.
- Here we select all rows where the country is equal to `USA`

In [ ]:
df[df["Country"] == "USA"]

- Here we filter for all rows whose age column is at least 30

In [ ]:
df[df["Age"] >= 30]

## Basic Statistics with Pandas

- We can compute some basic statistics manually on a selected column by using various pandas methods.

- Compute the **minimum** value in the 'Age' column.

In [ ]:
df['Age'].min()

- Compute the **maximum** value in the 'Age' column.

In [ ]:
df['Age'].max()

- Compute the **mean (average)** of the 'Age' column.

In [ ]:
df['Age'].mean()

- Compute the **standard deviation** of the 'Age' column.

In [ ]:
df['Age'].std()

## Plotting with Pandas

- Use `.plot()` to make a bar chart of Age by Name using built-in pandas plotting.

In [ ]:
df.plot(kind='bar', x="Name", y="Age")

- Here we make a pie chart of `Country`

In [ ]:
df["Country"].value_counts().plot(kind="pie")

## Reading and Writing CSV Files

- Read a CSV file into a DataFrame using `pd.read_csv()`.

### Example: Reading and Writing a Realistic CSV File
We simulate a fraud detection dataset with 100 transactions. Let's read it using pandas.

In [ ]:
df = pd.read_csv('fraud-detection.csv')
df.sample(5)

- Add a new column that tracks whether the amount is 'high' (>150) or 'low'.
- Here we use a lambda function and the `.apply` method in pandas.
- `.apply(func)` applies `func` to the selected column. Here `func` is a lambda.

In [ ]:
df['amount_level'] = df['amount'].apply(lambda x: 'high' if x > 150 else 'low')
df.sample(5)

- Save the updated DataFrame to a new CSV file.

In [ ]:
df.to_csv('fraud-detection-updated.csv', index=False)

## Useful Method Table

- Here is a large collection of useful methods in pandas and what they do.

| Pandas Method                  | Description                                                                 |
|-------------------------------|-----------------------------------------------------------------------------|
| `df.head()`                   | Returns the first 5 rows of the DataFrame.                                  |
| `df.tail()`                   | Returns the last 5 rows of the DataFrame.                                   |
| `df.info()`                   | Displays summary information including column types and non-null counts.    |
| `df.describe()`               | Computes summary statistics for numeric columns.                            |
| `df.shape`                   | Returns a tuple of (number of rows, number of columns).                     |
| `df.columns`                 | Returns the list of column names.                                           |
| `df.index`                   | Returns the index (row labels) of the DataFrame.                            |
| `df.dtypes`                  | Returns the data type of each column.                                       |
| `df['col'].value_counts()`   | Counts the number of occurrences of each unique value in the column.        |
| `df['col'].unique()`         | Returns the unique values in a column.                                      |
| `df['col'].nunique()`        | Returns the number of unique values in a column.                            |
| `df.isnull()`                | Returns a DataFrame of the same shape with True for missing values.         |
| `df.isnull().sum()`          | Counts the number of missing values in each column.                         |
| `df.fillna(value)`           | Fills missing values with a specified value.                                |
| `df.dropna()`                | Removes rows with any missing values.                                       |
| `df.sort_values(by='col')`   | Sorts the DataFrame by the values in the given column.                      |
| `df.groupby('col')`          | Groups the DataFrame by a column and returns a GroupBy object.              |
| `df['col'].map(func)`        | Applies a function to each element in a column.                             |
| `df.apply(func, axis=1)`     | Applies a function across rows or columns.                                  |
| `df.drop('col', axis=1)`     | Drops a column from the DataFrame.                                          |
| `df.drop(index, axis=0)`     | Drops a row from the DataFrame.                                             |
| `df.to_csv('file.csv')`      | Writes the DataFrame to a CSV file.                                         |
| `pd.read_csv('file.csv')`    | Reads a CSV file into a DataFrame.                                          |

***
# CLASSWORK

### 1. Fill in the Blanks
Replace each `????` with the correct term:

1. Pandas is built on top of the ???? library.
2. A one-dimensional labeled array is called a ???? in Pandas.
3. The method to show basic statistics of a DataFrame is `df.????()`.
4. To access the first 5 rows of a DataFrame, we use `df.????()`.
5. To save a DataFrame to a CSV file, we use `df.????('filename.csv')`.

### 2. Create and Analyze DataFrame

| Product     | Price | Quantity |
|-------------|-------|----------|
| Keyboard    | 49.99 | 10       |
| Mouse       | 19.99 | 25       |
| Monitor     | 149.99| 7        |
| USB Cable   | 5.99  | 50       |
| Webcam      | 89.99 | 5        |
| Laptop Stand| 29.99 | 12       |

- Make a pandas dataframe `items` from the information in the table above. Your dataframe should have columns `Product`, `Price` and `Quantity`.  
- Print the first 3 rows of `items`
- Select the `Product` column.
- Find and print the mean and max of `Price`.

### 3. Read, Modify and Write CSV

- Read the `fraud-detection.csv` file as a pandas dataframe called `fraud`.
- print a sample of 10 rows.
- How many rows does this dataframe have?  
- Add a new column to the dataframe called `duration_level` which has value `"long"` for rows with duration at least 170 seconds, otherwise `"short"`
  - Hint: You can use either a list comprehension or `.apply` with a lambda.
- Find how many rows have a `long` transaction duration.
- Save the new DataFrame to a different csv file called `"fraud-transaction-updated2.csv"`
- **Advanced**: select all rows whose transaction duration is above average and whose amount is above average.